# Site settings
title: "Tom Harris"
author:
  name:     "Tom Harris"
  email:    "tkmharris@gmail.com"
  twitter:  "@Eschatom"
  mastodon: "@tomharris@mastodon.social"
title: "Tom Harris"
url: "www.tkmharris.net"

exclude: [archived, notes, README.md, LICENSE.md, deploy.sh]
include: [.htaccess]

gems: [jekyll-last-modified-at]

# Build settings
markdown: rdiscount
mathjax: true
permalink: pretty
highlighter: rouge
